# Site settings
title: Nik M
subtitle: by satuhearty
email: nikm@babynik.com
description: My Journey To The World
baseurl: "/nikmalik" # the subpath of your site, e.g. /blog
url: "https://satuhearty.github.io/" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Boston
state: MA
zip_code: 55555
country: United States of America
phone: (217) 377-0469

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, webpack, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
